"""A small, constrained Agentic-RAG planner for local investment workflows."""

from __future__ import annotations

import re
from typing import Any, Iterable, Mapping

from .advanced_rag import AdvancedRAG
from .knowledge import DISTRICT_REFERENCE_POINTS, KnowledgeRepository, json_list


class InvestmentAgent:
    """Choose a bounded local tool plan; it never emits SQL generated by an LLM."""

    ALLOWED_TOOLS = {
        "sql_company_search",
        "geo_search",
        "hybrid_rag",
        "graph_expand",
        "park_compare",
        "landing_package",
    }

    def __init__(self, repository: KnowledgeRepository, rag: AdvancedRAG) -> None:
        self.repository = repository
        self.rag = rag

    def answer(
        self,
        *,
        query: str,
        district: str | None = None,
        sector: str | None = None,
        mode: str = "auto",
        company_ids: Iterable[str] | None = None,
        park_ids: Iterable[str] | None = None,
        latitude: float | None = None,
        longitude: float | None = None,
        radius_km: float | None = None,
        project_name: str | None = None,
    ) -> dict[str, Any]:
        query = query.strip()
        selected_mode = self._plan_mode(query, mode, district=district, sector=sector, latitude=latitude, longitude=longitude)
        plan = self._plan(selected_mode, query)
        if selected_mode == "sql":
            payload = self.repository.list_companies(query="" if self._is_structured_query(query) else query, district=district or self._district_from_query(query), sector=sector or self._sector_from_query(query), company_ids=company_ids, page_size=100)
            return self._sql_response(query, payload, plan)
        if selected_mode == "geo":
            return self._geo_response(query, district=district, latitude=latitude, longitude=longitude, radius_km=radius_km, plan=plan)
        if selected_mode == "graph":
            return self._graph_response(query, district=district, sector=sector, company_ids=company_ids, plan=plan)
        if selected_mode == "park":
            comparison = self.repository.compare_parks(park_ids or [])
            return {
                "query": query,
                "execution": {"mode": "park_compare", "rag_called": False, "tool_calls": plan},
                "park_comparison": comparison,
                "sources": self._sources_from_parks(comparison.get("parks", [])),
                "report": {"overview": "园区对标仅展示已入库公开事实；未知供给和优惠信息保持待核验。"},
            }
        if selected_mode == "landing":
            package = self.repository.landing_package(project_name=project_name or query, district=district)
            return {
                "query": query,
                "execution": {"mode": "landing_package", "rag_called": False, "tool_calls": plan},
                "landing_package": package,
                "sources": self._sources_from_landing(package),
                "report": {"overview": "已按政务办事、生活配套、交通区位组织本地化落地核验包。"},
            }
        if selected_mode == "project":
            return self._project_response(query, district=district, sector=sector, park_ids=park_ids, project_name=project_name, plan=plan)
        return self._hybrid_response(query, district=district, sector=sector, plan=plan)

    def _plan_mode(self, query: str, requested: str, *, district: str | None, sector: str | None, latitude: float | None, longitude: float | None) -> str:
        if requested and requested != "auto":
            return requested
        lower = query.casefold()
        if any(term in lower for term in ("半径", "附近", "车程", "公里", "距离", "地理")) or latitude is not None or longitude is not None:
            return "geo"
        if any(term in lower for term in ("上游", "下游", "图谱", "关系", "关联路径")):
            return "graph"
        if any(term in lower for term in ("园区对比", "园区比较", "独资设立", "洽谈要点")):
            return "park"
        if any(term in lower for term in ("落地配套", "政务办事", "生活配套", "交通区位")) and not any(term in lower for term in ("企业", "供应商", "产业链")):
            return "landing"
        if ("独资" in lower or "项目" in lower) and any(term in lower for term in ("园区", "落地", "政务", "配套", "招商")):
            return "project"
        if (district or sector) and any(term in lower for term in ("列出", "筛选", "企业id", "企业 ID", "按id", "精确")):
            return "sql"
        return "hybrid"

    @classmethod
    def _plan(cls, mode: str, query: str) -> list[dict[str, str]]:
        mapping = {
            "sql": [("sql_company_search", "参数化精确企业筛选")],
            "geo": [("geo_search", "RTree 初筛、Haversine 和本地道路系数估算")],
            "graph": [("hybrid_rag", "识别图谱种子企业"), ("graph_expand", "最多两跳的可溯源关系扩展")],
            "park": [("park_compare", "园区指标与洽谈支持")],
            "landing": [("landing_package", "政务、生活、交通配套包")],
            "project": [
                ("hybrid_rag", "企业与产业链证据"),
                ("park_compare", "园区对标与独资洽谈支持"),
                ("landing_package", "政务、生活、交通配套"),
            ],
            "hybrid": [("hybrid_rag", "上下文、BM25、BGE-M3、RRF、Cross-Encoder")],
        }
        return [{"tool": tool, "reason": reason, "allowed": str(tool in cls.ALLOWED_TOOLS).lower()} for tool, reason in mapping.get(mode, mapping["hybrid"])]

    def _hybrid_response(self, query: str, *, district: str | None, sector: str | None, plan: list[dict[str, str]]) -> dict[str, Any]:
        result = self.rag.retrieve(query, district=district, sector=sector, top_k=10)
        companies = result["companies"]
        matches = self._match_groups(companies, query)
        sources = self._sources_from_chunks(result["chunks"])
        return {
            "query": query,
            "execution": {"mode": "hybrid_rag", "rag_called": True, "tool_calls": plan},
            "retrieval_trace": result["trace"],
            "matches": matches,
            "evidence": result["chunks"],
            "sources": sources,
            "report": self._report(query, companies, matches),
        }

    def _graph_response(
        self,
        query: str,
        *,
        district: str | None,
        sector: str | None,
        company_ids: Iterable[str] | None,
        plan: list[dict[str, str]],
    ) -> dict[str, Any]:
        hybrid = self.rag.retrieve(query, district=district, sector=sector, top_k=12)
        seeds = list(company_ids or []) or self._mentioned_company_ids(query) or [item["company_id"] for item in hybrid["companies"][:4]]
        graph = self.repository.graph_expand(seeds, max_hops=2, limit=32)
        companies = hybrid["companies"]
        for node in graph.get("nodes", []):
            if node.get("node_type") == "company":
                company_id = str(node.get("node_id", "")).removeprefix("company:")
                if not any(item["company_id"] == company_id for item in companies):
                    companies.extend(self.repository.company_by_ids([company_id]))
        matches = self._match_groups(companies, query)
        sources = self._sources_from_chunks(hybrid["chunks"])
        for edge in graph.get("edges", []):
            sources.extend(self.repository.source_cards(edge.get("source_ids", [])))
        return {
            "query": query,
            "execution": {"mode": "graph_rag", "rag_called": True, "tool_calls": plan},
            "retrieval_trace": hybrid["trace"],
            "matches": matches,
            "evidence": hybrid["chunks"],
            "graph": graph,
            "sources": self._unique_sources(sources),
            "report": self._report(query, companies, matches, graph=True),
        }

    def _project_response(
        self,
        query: str,
        *,
        district: str | None,
        sector: str | None,
        park_ids: Iterable[str] | None,
        project_name: str | None,
        plan: list[dict[str, str]],
    ) -> dict[str, Any]:
        hybrid = self._hybrid_response(query, district=district, sector=sector, plan=plan[:1])
        comparison = self.repository.compare_parks(park_ids or [])
        package = self.repository.landing_package(project_name=project_name or query, district=district)
        sources = self._unique_sources([
            *hybrid["sources"],
            *self._sources_from_parks(comparison.get("parks", [])),
            *self._sources_from_landing(package),
        ])
        return {
            "query": query,
            "execution": {"mode": "agentic_project", "rag_called": True, "tool_calls": plan},
            "retrieval_trace": hybrid.get("retrieval_trace", {}),
            "matches": hybrid["matches"],
            "evidence": hybrid["evidence"],
            "park_comparison": comparison,
            "landing_package": package,
            "sources": sources,
            "report": {
                **hybrid["report"],
                "overview": "单一轻量 Agent 已联动企业产业链、园区招商对标与落地配套三类知识库；每一项均需以所列来源进行业务核验。",
                "recommendations": [
                    "先以企业证据卡确认产品、能力和当前合作意向，再形成靶向招商名单。",
                    "园区试点与产业适配仅用于初步对标；土地、厂房、能耗和优惠条件必须向属地核实。",
                    "将政务、人才/生活和物流事项纳入同一项目台账，明确责任人和下一步。",
                ],
            },
        }

    def _sql_response(self, query: str, payload: Mapping[str, Any], plan: list[dict[str, str]]) -> dict[str, Any]:
        companies = list(payload.get("items", []))
        matches = self._match_groups(companies, query)
        sources: list[dict[str, Any]] = []
        for company in companies:
            sources.extend(company.get("sources", []))
        return {
            "query": query,
            "execution": {"mode": "sql", "rag_called": False, "tool_calls": plan},
            "companies": companies,
            "matches": matches,
            "sources": self._unique_sources(sources),
            "report": {"overview": f"SQL 精确筛选返回 {len(companies)} 家企业；该路径未调用 RAG。", "caveats": ["字段值来自已入库公开资料；空白和待核验字段不做推断。"]},
        }

    def _geo_response(
        self,
        query: str,
        *,
        district: str | None,
        latitude: float | None,
        longitude: float | None,
        radius_km: float | None,
        plan: list[dict[str, str]],
    ) -> dict[str, Any]:
        point = DISTRICT_REFERENCE_POINTS.get(district or self._district_from_query(query) or "", DISTRICT_REFERENCE_POINTS["常州市"])
        result = self.repository.geo_search(latitude=latitude if latitude is not None else point[0], longitude=longitude if longitude is not None else point[1], radius_km=radius_km or self._radius_from_query(query) or 20, entity_type="company")
        sources: list[dict[str, Any]] = []
        for item in result["items"]:
            sources.extend(item.get("sources", []))
        return {
            "query": query,
            "execution": {**result["execution"], "tool_calls": plan},
            "geo": result,
            "companies": result["items"],
            "sources": self._unique_sources(sources),
            "report": {"overview": "此结果使用 SQLite 地理索引与本地道路系数估算，未调用 RAG。", "caveats": ["企业坐标为公开坐标或明确标识的演示参考点；车程不是实时导航。"]},
        }

    def _mentioned_company_ids(self, query: str) -> list[str]:
        all_companies = self.repository.list_companies(page_size=100)["items"]
        found: list[str] = []
        for company in all_companies:
            name = str(company.get("name") or "")
            aliases = [name, *company.get("aliases", [])]
            for candidate in aliases:
                candidate = str(candidate).strip()
                if len(candidate) >= 3 and candidate in query:
                    found.append(str(company["company_id"]))
                    break
                # Companies are commonly referenced by the distinctive name
                # fragment before legal suffixes, e.g. “蜂巢能源”.
                compact = re.split(r"科技|股份|有限|集团|分公司", candidate)[0]
                if len(compact) >= 3 and compact in query:
                    found.append(str(company["company_id"]))
                    break
        return list(dict.fromkeys(found))

    def _district_from_query(self, query: str) -> str | None:
        for district in self.repository.filter_options().get("districts", []):
            if district and district in query:
                return district
        return None

    def _sector_from_query(self, query: str) -> str | None:
        for sector in self.repository.filter_options().get("sectors", []):
            if sector and (sector in query or ("新能源" in query and "新能源" in sector)):
                return sector
        return None

    @staticmethod
    def _radius_from_query(query: str) -> float | None:
        match = re.search(r"(\d+(?:\.\d+)?)\s*(?:km|公里|千米)", query, flags=re.IGNORECASE)
        return float(match.group(1)) if match else None

    @staticmethod
    def _is_structured_query(query: str) -> bool:
        return any(token in query.casefold() for token in ("列出", "筛选", "企业id", "企业 id", "按id", "精确"))

    @staticmethod
    def _match_groups(companies: Iterable[Mapping[str, Any]], query: str) -> dict[str, Any]:
        suppliers: list[dict[str, Any]] = []
        customers: list[dict[str, Any]] = []
        partners: list[dict[str, Any]] = []
        all_matches: list[dict[str, Any]] = []
        for source in companies:
            company = dict(source)
            text = " ".join([company.get("industry", ""), *company.get("products", []), *company.get("supply_chain_role", [])])
            company["match_reason"] = "公开资料中的产品、能力、产业链角色与本次需求存在潜在关联；不代表已建立合作。"
            company["match_type"] = "potential"
            if any(token in text for token in ("材料", "正极", "负极", "供应")):
                suppliers.append(company)
            elif any(token in text for token in ("整车", "汽车", "应用", "客户")):
                customers.append(company)
            else:
                partners.append(company)
            all_matches.append(company)
        return {"suppliers": suppliers[:5], "customers": customers[:5], "partners": partners[:5], "all_matches": all_matches[:10], "rationale": "全部匹配均为基于公开资料的潜在线索，需要以规格、产能、认证和商务意向进行下一轮核验。"}

    @staticmethod
    def _report(query: str, companies: Iterable[Mapping[str, Any]], matches: Mapping[str, Any], *, graph: bool = False) -> dict[str, Any]:
        items = list(companies)
        names = "、".join(str(item.get("name")) for item in items[:4]) or "暂无足够企业证据"
        return {
            "overview": f"围绕“{query}”，本地证据库检出 {len(items)} 家候选企业：{names}。结论为招商研判线索，不代表已形成商业关系。",
            "supply_chain": "本次结果按公开产品、能力和产业链角色组织；图谱边中的 inferred/potential 标签表示系统归纳而非已证实交易。" if graph else "本次结果使用上下文检索、BM25、BGE-M3、RRF 与 Cross-Encoder 重排，候选企业均可回链至公开来源。",
            "recommendations": [
                "优先核验排名靠前企业的产品规格、产能、质量/认证与当前业务意向。",
                "把匹配名单纳入台账，明确负责人、下一步和需补录的信息。",
                "园区、配套和距离类信息仅作为前期研判依据，应在项目洽谈阶段二次确认。",
            ],
            "caveats": ["公开资料为空的字段保持未知。", "潜在供应商、客户或合作方均不代表已存在商业关系。"],
        }

    @staticmethod
    def _sources_from_chunks(chunks: Iterable[Mapping[str, Any]]) -> list[dict[str, Any]]:
        output: list[dict[str, Any]] = []
        for chunk in chunks:
            output.extend(chunk.get("sources", []))
            company = chunk.get("company")
            if isinstance(company, Mapping):
                output.extend(company.get("sources", []))
        return InvestmentAgent._unique_sources(output)

    @staticmethod
    def _sources_from_parks(parks: Iterable[Mapping[str, Any]]) -> list[dict[str, Any]]:
        return InvestmentAgent._unique_sources(source for park in parks for source in park.get("sources", []))

    @staticmethod
    def _sources_from_landing(package: Mapping[str, Any]) -> list[dict[str, Any]]:
        return InvestmentAgent._unique_sources(
            source for section in package.get("sections", []) for item in section.get("items", []) for source in item.get("sources", [])
        )

    @staticmethod
    def _unique_sources(sources: Iterable[Mapping[str, Any]]) -> list[dict[str, Any]]:
        seen: set[str] = set()
        output: list[dict[str, Any]] = []
        for source in sources:
            if not isinstance(source, Mapping):
                continue
            identity = str(source.get("url") or source.get("source_id") or "")
            if not identity or identity in seen:
                continue
            seen.add(identity)
            output.append(dict(source))
        return output
